// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package signaling_server

import (
	"github.com/google/wire"
	"github.com/pipe-network/signaling-server/application"
	"github.com/pipe-network/signaling-server/infrastructure/providers"
	"github.com/pipe-network/signaling-server/interface/controllers"
)

// Injectors from wire.go:

func InitializeMainApplication() application.MainApplication {
	upgrader := providers.ProvideUpgrader()
	signalingController := controllers.NewSignalingController(upgrader)
	mainApplication := application.NewMainApplication(signalingController)
	return mainApplication
}

// wire.go:

var Providers = wire.NewSet(providers.ProvideUpgrader)
