// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package signaling_server

import (
	"github.com/google/wire"
	"github.com/pipe-network/signaling-server/application"
	"github.com/pipe-network/signaling-server/application/services"
	"github.com/pipe-network/signaling-server/infrastructure/providers"
	"github.com/pipe-network/signaling-server/infrastructure/storages"
	"github.com/pipe-network/signaling-server/interface/controllers"
)

// Injectors from wire.go:

func InitializeMainApplication() (application.MainApplication, error) {
	upgrader := providers.ProvideUpgrader()
	keyPairLocalStorageAdapter, err := storages.NewKeyPairLocalStorageAdapter()
	if err != nil {
		return application.MainApplication{}, err
	}
	saltyRTCService := services.NewSaltyRTCService(keyPairLocalStorageAdapter)
	signalingController := controllers.NewSignalingController(upgrader, saltyRTCService)
	mainApplication := application.NewMainApplication(signalingController)
	return mainApplication, nil
}

// wire.go:

var Providers = wire.NewSet(providers.ProvideUpgrader)
